### ISSUE TITLE
Release notes for latest version

### ISSUE THREAD

**Issue by ngirard** [Darakah/obsidian-gallery#5]
Heya,
would you mind amending the *Release notes* section of the README ?

Cheers, and thanks for your work !

**Comment by Darakah** [comment]
@ngirard ,

Added main highlights to release notes https://github.com/Darakah/obsidian-gallery#release-notes

Will add more detailed info to the README following the next update, for now please note that you can obtain usage information for all code blocks (`gallery` and `gallery-info`) from the block itself (when non valid info is written, the block will display its usage, so simply write down an empty block to view it). 

If you have any questions, feel free to ask them here as I tagged this issue with documentation or refer to https://github.com/Darakah/obsidian-gallery/issues/1#issuecomment-816892220 for slightly more explanations regarding the recent release.

**Comment by ngirard** [comment]
Great, thanks !

> you can obtain usage information for all code blocks (gallery and gallery-info) from the block itself

Indeed, that's good to know !
