### ISSUE TITLE
[Bug] Duplicated Img file if plugin enabled on another device

### ISSUE THREAD

**Issue by SlRvb** [Darakah/obsidian-gallery#6]
I turned on the plugin on mobile and it resulting in duplicated Img files for those same images I already had in the vault:

I think maybe the best way to avoid this is to have the plugin search `Img` files for linked image file names that match the ones inside the note before creating a new one?
![qHYZF2woZh](https://user-images.githubusercontent.com/54087190/114286713-178ce600-9a16-11eb-9e94-ec7216e917ed.png)

**Comment by Darakah** [comment]
@SlRvb Thanks for reporting this!

I believe it is fixed with the `0.5.2`, feel free to re-open this issue if the problem happens again.
