### ISSUE TITLE
Backlink Panel Doesnt Work for Active Media

### ISSUE THREAD

**Issue by denemier** [Darakah/obsidian-gallery#9]
when i click on a media file which shows as popup, and a sidebar with image info as you now but when i click to backlinks tab on the sidebar i cant see all related notes where the file is backlinked.

a way around i found is click the media with right mouse button so instead of opening a popup i can go directly to the native obsidian file and backlink on sidebar works fine

**Comment by Darakah** [comment]
I don't understand. 

You mean when you open the info file of an image, it has no backlinks?

**Comment by denemier** [comment]
no, when we just left click the image on your gallery it shows it as popup but this doesnt activate the backlinks option
you can check my screenshot
![screenshot](https://user-images.githubusercontent.com/63566495/115226630-2d9c4580-a0ab-11eb-9399-ffa86661c815.png)

**Comment by Darakah** [comment]
Because that is not a feature ...
The backlinks is an obsidian core plugin and not related to the gallery plugin.
Will add the option to show all files that this image is linked to inside the info block
https://github.com/Darakah/obsidian-gallery/issues/4#issuecomment-817154303
